### ISSUE TITLE
Two more corrections Fullset.py and Dice_modeller.py

### ISSUE THREAD

**Issue by girrrrrrr2** [George-Britton/DiceModeller#2]
Was going through getting everything to work and I found two more typos/errors

Fullset.py is missing a comma after outputFolder on line 18
and
Dice_Modeller.py line 198 it says s.path.expanduser instead of os.path.expanduser

Otherwise once I made those changes locally, everything appears to be working fully, and I have been able to make and export some dice!

Thank you for releasing this for everyone to use!

**Comment by George-Britton** [comment]
Damn, I should've had you around when I was writing this! Great work! I'm glad someone's getting some use out of it :)
