### ISSUE TITLE
Getting ""add_mesh_extra_objects" error when running script.

### ISSUE THREAD

**Issue by dixonsm** [George-Britton/DiceModeller#3]
When I run any of the scripts I get the following error: 

File "\Text", line 4, in <module>
File C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py" , line 109, in_call_
 ret = _op_call(self.idname_py(), kw)
       ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: Add-on not loaded: "add_mesh_extra_objects", cause: No module named 'add_mesh_extra_objects'

**Comment by dustin-l-brown** [comment]
You can comment out this line if you have the "Extra Mesh Objects" add-on enabled.
